name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy_artifact:
    name: "Deploy Artifact"
    uses: scmspain/backend-di--python-lib-template/.github/workflows/deploy-artifact.yml@master
    with:
      slack-notification-username: "Python Library Template"
    secrets:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PWD: ${{ secrets.ARTIFACTORY_PWD }}
      SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST: ${{ secrets.SONAR_HOST }}
